# Generated by Django 5.1.6 on 2025-03-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Taskname',
            new_name='task_name',
        ),
    ]
